Repository kamilmielnik/scrabble-solver, pull requests merged in 2021-01, with the labels that each got.

#24 Floating icon to toggle typing direction
  packages/scrabble-solver/src/components/Board/Board.tsx
  packages/scrabble-solver/src/components/Board/components/Cell/Cell.module.scss
  packages/scrabble-solver/src/components/Board/components/Cell/Cell.tsx
  packages/scrabble-solver/src/components/Board/hooks/useGrid.ts
  packages/scrabble-solver/src/components/Dictionary/Dictionary.module.scss
  packages/scrabble-solver/src/components/Key/Key.module.scss
  packages/scrabble-solver/src/components/Key/Key.tsx
  packages/scrabble-solver/src/components/KeyMap/KeyMap.tsx
  packages/scrabble-solver/src/components/KeyMap/components/Mapping/Mapping.module.scss
  packages/scrabble-solver/src/components/KeyMap/components/Mapping/Mapping.tsx
  packages/scrabble-solver/src/components/KeyMap/mapping.ts
  packages/scrabble-solver/src/components/KeyMap/mapping.tsx
  packages/scrabble-solver/src/components/Results/Results.module.scss
  packages/scrabble-solver/src/components/Settings/Settings.tsx
  packages/scrabble-solver/src/components/Settings/components/AutoGroupTilesSetting/AutoGroupTilesSetting.tsx
  packages/scrabble-solver/src/components/Settings/components/AutoGroupTilesSetting/types.ts
  packages/scrabble-solver/src/components/Settings/components/ConfigSetting/ConfigSetting.tsx
  packages/scrabble-solver/src/components/Settings/components/OtherSettings/OtherSettings.tsx
  packages/scrabble-solver/src/components/Settings/components/OtherSettings/index.ts
  packages/scrabble-solver/src/components/Settings/components/index.ts
  packages/scrabble-solver/src/components/Sidebar/components/Section/Section.module.scss
  packages/scrabble-solver/src/components/Splash/Splash.module.scss
  packages/scrabble-solver/src/i18n/en.json
  packages/scrabble-solver/src/i18n/pl.json
  packages/scrabble-solver/src/icons/arrowDown.svg
  packages/scrabble-solver/src/icons/arrowLeft.svg
  packages/scrabble-solver/src/icons/arrowRight.svg
  packages/scrabble-solver/src/icons/arrowUp.svg
  packages/scrabble-solver/src/icons/index.ts
  packages/scrabble-solver/src/lib/index.ts
  packages/scrabble-solver/src/lib/isCtrl.ts
  packages/scrabble-solver/src/state/selectors.ts
  packages/scrabble-solver/src/state/slices/settingsInitialState.ts
  packages/scrabble-solver/src/state/slices/settingsSlice.ts
  packages/scrabble-solver/src/state/slices/tilesSlice.ts
  packages/scrabble-solver/src/styles/global.scss
  packages/scrabble-solver/src/styles/variables.scss
Labels: Type - Feature

#29 Organize buttons
  packages/scrabble-solver/src/components/NavButtons/NavButtons.module.scss
  packages/scrabble-solver/src/components/NavButtons/NavButtons.tsx
  packages/scrabble-solver/src/components/NavButtons/index.ts
  packages/scrabble-solver/src/components/index.ts
  packages/scrabble-solver/src/pages/index.module.scss
  packages/scrabble-solver/src/pages/index.tsx
Labels: Type - Feature

#35 Backspace/Del on the board should also move focus
  packages/scrabble-solver/src/components/Board/components/Cell/Cell.tsx
  packages/scrabble-solver/src/components/Board/hooks/useGrid.ts
Labels: Type - Feature

#36 Add labels to buttons
  packages/scrabble-solver/src/components/Button/Button.module.scss
  packages/scrabble-solver/src/components/Button/Button.tsx
  packages/scrabble-solver/src/components/Button/Content.tsx
  packages/scrabble-solver/src/components/Button/Link.tsx
  packages/scrabble-solver/src/components/Button/index.ts
  packages/scrabble-solver/src/components/Dictionary/Dictionary.module.scss
  packages/scrabble-solver/src/components/IconButton/IconButton.module.scss
  packages/scrabble-solver/src/components/IconButton/IconButton.tsx
  packages/scrabble-solver/src/components/IconButton/index.ts
  packages/scrabble-solver/src/components/Key/Key.module.scss
  packages/scrabble-solver/src/components/KeyMap/KeyMap.tsx
  packages/scrabble-solver/src/components/KeyMap/mapping.tsx
  packages/scrabble-solver/src/components/NavButtons/NavButtons.module.scss
  packages/scrabble-solver/src/components/NavButtons/NavButtons.tsx
  packages/scrabble-solver/src/components/Results/Results.module.scss
  packages/scrabble-solver/src/components/Screen/Screen.tsx
  packages/scrabble-solver/src/components/Sidebar/Sidebar.module.scss
  packages/scrabble-solver/src/components/Sidebar/Sidebar.tsx
  packages/scrabble-solver/src/components/index.ts
  packages/scrabble-solver/src/i18n/en.json
  packages/scrabble-solver/src/i18n/pl.json
  packages/scrabble-solver/src/styles/global.scss
  packages/scrabble-solver/src/styles/variables.scss
Labels: Type - Feature

#37 Floating icon to toggle blank
  packages/scrabble-solver/src/components/Board/components/Cell/Button.tsx
  packages/scrabble-solver/src/components/Board/components/Cell/Cell.module.scss
  packages/scrabble-solver/src/components/Board/components/Cell/Cell.tsx
  packages/scrabble-solver/src/i18n/en.json
  packages/scrabble-solver/src/i18n/pl.json
Labels: Type - Feature

#38 Add more logging
  packages/constants/src/index.ts
  packages/models/src/Board.ts
  packages/scrabble-solver/src/api/getServerLoggingData.ts
  packages/scrabble-solver/src/api/index.ts
  packages/scrabble-solver/src/pages/api/dictionary/[locale]/[word].ts
  packages/scrabble-solver/src/pages/api/solve.ts
  packages/scrabble-solver/src/pages/api/visit.ts
  packages/scrabble-solver/src/pages/index.tsx
  packages/scrabble-solver/src/sdk/index.ts
  packages/scrabble-solver/src/sdk/visit.ts
  packages/scrabble-solver/src/state/actions.ts
  packages/scrabble-solver/src/state/index.ts
  packages/scrabble-solver/src/state/sagas.ts
  packages/scrabble-solver/src/types/index.ts
Labels: Type - Feature

#46 Clicking inside an icon of non-first unchecked radio button does not select that option
  packages/scrabble-solver/src/components/Radio/Radio.module.scss
Labels: Type - Bug

#47 Settings sidebar can be seen above the splash on first visit and page refresh
  packages/scrabble-solver/src/components/Splash/Splash.tsx
  packages/scrabble-solver/src/pages/index.tsx
Labels: Type - Bug

#48 Validate max number of blanks passed in tiles in API
  packages/models/src/Config.ts
  packages/scrabble-solver/src/components/Button/Button.module.scss
  packages/scrabble-solver/src/pages/api/solve.ts
Labels: Type - Bug

#49 Board & titles should be in <form>
  packages/scrabble-solver/src/components/Board/components/Cell/Cell.tsx
  packages/scrabble-solver/src/components/Results/SolveButton.tsx
  packages/scrabble-solver/src/components/Tiles/Tiles.tsx
  packages/scrabble-solver/src/i18n/pl.json
  packages/scrabble-solver/src/pages/api/solve.ts
  packages/scrabble-solver/src/pages/index.tsx
Labels: Type - a11y

#51 Board does not shrink when viewport shrinks
  packages/scrabble-solver/src/components/PlainTiles/PlainTiles.module.scss
  packages/scrabble-solver/src/components/Screen/Screen.module.scss
  packages/scrabble-solver/src/components/Screen/Screen.tsx
  packages/scrabble-solver/src/components/Splash/Splash.module.scss
  packages/scrabble-solver/src/components/Splash/Splash.tsx
  packages/scrabble-solver/src/components/Tile/Tile.tsx
  packages/scrabble-solver/src/components/Well/Well.tsx
  packages/scrabble-solver/src/pages/index.tsx
  packages/scrabble-solver/src/styles/animations.scss
Labels: Type - Bug

#55 Build does not work on Windows
  README.md
  package-lock.json
  package.json
  packages/configs/package.json
  packages/constants/package.json
  packages/logger/package.json
  packages/models/package.json
  packages/scrabble-solver/.env
  packages/scrabble-solver/package-lock.json
  packages/scrabble-solver/package.json
  packages/solver/package.json
Labels: Type - Bug

#56 Replace "request" dependency in root package
  package.json
  scripts/utils.js
Labels: Type - Dependencies

#57 Move all common dependencies to root package
  package-lock.json
  package.json
  packages/configs/package-lock.json
  packages/configs/package.json
  packages/constants/package-lock.json
  packages/constants/package.json
  packages/logger/package-lock.json
  packages/logger/package.json
  packages/models/package-lock.json
  packages/models/package.json
  packages/scrabble-solver/package-lock.json
  packages/scrabble-solver/package.json
  packages/solver/package-lock.json
  packages/solver/package.json
Labels: Type - Refactoring

#50 French support
  package.json
  packages/configs/src/getConfig.ts
  packages/configs/src/getLocaleConfig.ts
  packages/configs/src/literaki.ts
  packages/configs/src/scrabble.ts
  packages/scrabble-solver/src/api/index.ts
  packages/scrabble-solver/src/api/translateFr.ts
  packages/scrabble-solver/src/api/validateLocale.ts
  packages/scrabble-solver/src/components/Settings/components/LocaleSetting/options.ts
  packages/scrabble-solver/src/i18n/fr.json
  packages/scrabble-solver/src/i18n/index.ts
  packages/scrabble-solver/src/icons/flagFr.svg
  packages/scrabble-solver/src/icons/index.ts
  packages/scrabble-solver/src/lib/detectLocale.ts
  packages/scrabble-solver/src/lib/isLocale.ts
  packages/scrabble-solver/src/pages/api/dictionary/[locale]/[word].ts
  packages/scrabble-solver/src/pages/api/solve.ts
  packages/scrabble-solver/src/types/index.ts
  scripts/prepare-fr-dictionaries.js
Labels: Priority - Must have, Size - M, Type - Feature

#58 Refactor "Locale" type to an enum
  package-lock.json
  packages/configs/src/configs.ts
  packages/configs/src/getConfig.ts
  packages/configs/src/getLocaleConfig.ts
  packages/configs/src/index.ts
  packages/configs/src/isConfigId.ts
  packages/configs/src/literaki.ts
  packages/configs/src/scrabble.ts
  packages/scrabble-solver/src/api/readLocaleDictionary.ts
  packages/scrabble-solver/src/api/validateConfigId.ts
  packages/scrabble-solver/src/api/validateLocale.ts
  packages/scrabble-solver/src/components/Settings/components/ConfigSetting/types.ts
  packages/scrabble-solver/src/components/Settings/components/LocaleSetting/LocaleSetting.tsx
  packages/scrabble-solver/src/components/Settings/components/LocaleSetting/options.ts
  packages/scrabble-solver/src/components/Settings/components/LocaleSetting/types.ts
  packages/scrabble-solver/src/i18n/index.ts
  packages/scrabble-solver/src/lib/detectLocale.ts
  packages/scrabble-solver/src/lib/isLocale.ts
  packages/scrabble-solver/src/pages/api/dictionary/[locale]/[word].ts
  packages/scrabble-solver/src/pages/api/solve.ts
  packages/scrabble-solver/src/sdk/findWordDefinition.ts
  packages/scrabble-solver/src/sdk/solve.ts
  packages/scrabble-solver/src/state/localStorage.ts
  packages/scrabble-solver/src/state/slices/settingsInitialState.ts
  packages/scrabble-solver/src/state/slices/settingsSlice.ts
  packages/scrabble-solver/src/types/index.ts
  packages/types/src/Locale.ts
  packages/types/src/index.ts
Labels: Type - Refactoring

#60 Implement "/dictionary" endpoint for French
  packages/scrabble-solver/src/api/normalizeDefinition.ts
  packages/scrabble-solver/src/api/translateEn.ts
  packages/scrabble-solver/src/api/translateFr.ts
  packages/scrabble-solver/src/api/translatePl.ts
  packages/scrabble-solver/src/i18n/fr.json
Labels: Type - Feature

#64 Issues with splash animation
  packages/scrabble-solver/src/components/Screen/Screen.tsx
  packages/scrabble-solver/src/components/Splash/Splash.module.scss
  packages/scrabble-solver/src/components/Splash/Splash.tsx
  packages/scrabble-solver/src/pages/index.tsx
Labels: Type - Bug

#68 Add "build" GitHub action
  .github/workflows/build.yml
  README.md
Labels: Type - Chore

#69 Upgrade dependencies
  package-lock.json
  package.json
  packages/scrabble-solver/package-lock.json
  packages/scrabble-solver/package.json
  packages/solver/package.json
Labels: Type - Dependencies

#70 Extract @scrabble-solver/word-definitions package
  packages/scrabble-solver/package-lock.json
  packages/scrabble-solver/package.json
  packages/scrabble-solver/src/api/index.ts
  packages/scrabble-solver/src/api/translateFr.ts
  packages/scrabble-solver/src/api/translatePl.ts
  packages/scrabble-solver/src/pages/api/dictionary/[locale]/[word].ts
  packages/word-definitions/package-lock.json
  packages/word-definitions/package.json
  packages/word-definitions/src/getEnglishWordDefinition.ts
  packages/word-definitions/src/getFrenchWordDefinition.ts
  packages/word-definitions/src/getPolishWordDefinition.ts
  packages/word-definitions/src/getWordDefinition.ts
  packages/word-definitions/src/index.ts
  packages/word-definitions/src/lib/index.ts
  packages/word-definitions/src/lib/normalizeDefinition.ts
  packages/word-definitions/src/lib/request.ts
  packages/word-definitions/tsconfig.json
Labels: Type - Refactoring

#74 Extract "@scrabble-solver/word-lists" package
  package-lock.json
  package.json
  packages/scrabble-solver/package-lock.json
  packages/word-lists/package-lock.json
  packages/word-lists/package.json
  packages/word-lists/src/getEnGbWordList.ts
  packages/word-lists/src/getEnUsWordList.ts
  packages/word-lists/src/getFrFrWordList.ts
  packages/word-lists/src/getPlPlWordList.ts
  packages/word-lists/src/index.ts
  packages/word-lists/src/lib/downloadFile.ts
  packages/word-lists/src/lib/downloadHtml.ts
  packages/word-lists/src/lib/extractWords.ts
  packages/word-lists/src/lib/findFirstWordIndex.ts
  packages/word-lists/src/lib/getHash.ts
  packages/word-lists/src/lib/getTempFilename.ts
  packages/word-lists/src/lib/getTxtWordList.ts
  packages/word-lists/src/lib/index.ts
  packages/word-lists/tsconfig.json
  scripts/dictionaries.js
  scripts/prepare-en-dictionaries.js
  scripts/prepare-fr-dictionaries.js
  scripts/prepare-pl-dictionary.js
  scripts/utils.js
Labels: Type - Refactoring

#79 Add README with package description to every package
  packages/configs/README.md
  packages/constants/README.md
  packages/dictionaries/README.md
  packages/logger/README.md
  packages/scrabble-solver/README.md
  packages/solver/README.md
  packages/types/README.md
  packages/word-definitions/README.md
  packages/word-lists/README.md
Labels: Type - Chore

#82 Custom 404 page
  packages/scrabble-solver/src/components/NotFound/NotFound.module.scss
  packages/scrabble-solver/src/components/NotFound/NotFound.tsx
  packages/scrabble-solver/src/components/NotFound/index.ts
  packages/scrabble-solver/src/components/index.ts
  packages/scrabble-solver/src/icons/dashCircleFill.svg
  packages/scrabble-solver/src/icons/index.ts
  packages/scrabble-solver/src/pages/404.tsx
Labels: Type - Feature

#83 Refactor @scrabble-solver/word-definitions to @scrabble-solver/wiktionary
  README.md
  packages/scrabble-solver/package.json
  packages/scrabble-solver/src/i18n/en.json
  packages/scrabble-solver/src/i18n/fr.json
  packages/scrabble-solver/src/i18n/pl.json
  packages/scrabble-solver/src/pages/api/dictionary/[locale]/[word].ts
  packages/wiktionary/README.md
  packages/wiktionary/package-lock.json
  packages/wiktionary/package.json
  packages/wiktionary/src/__tests__/dicare.input.json
  packages/wiktionary/src/__tests__/dicare.output.json
  packages/wiktionary/src/__tests__/fourty.input.json
  packages/wiktionary/src/__tests__/fourty.output.json
  packages/wiktionary/src/__tests__/mako.input.json
  packages/wiktionary/src/__tests__/mako.output.json
  packages/wiktionary/src/__tests__/man.input.json
  packages/wiktionary/src/__tests__/man.output.json
  packages/wiktionary/src/getWordDefinition.ts
  packages/wiktionary/src/index.ts
  packages/wiktionary/src/lib/index.ts
  packages/wiktionary/src/lib/normalizeDefinition.ts
  packages/wiktionary/src/lib/request.ts
  packages/wiktionary/src/lib/unique.ts
  packages/wiktionary/src/parseResponse.test.ts
  packages/wiktionary/src/parseResponse.ts
  packages/wiktionary/src/parseResponseHtml.ts
  packages/wiktionary/src/types.ts
  packages/wiktionary/tsconfig.json
  packages/word-definitions/README.md
  packages/word-definitions/src/getEnglishWordDefinition.ts
  packages/word-definitions/src/getFrenchWordDefinition.ts
  packages/word-definitions/src/getPolishWordDefinition.ts
  packages/word-definitions/src/getWordDefinition.ts
  packages/word-definitions/src/index.ts
  packages/word-definitions/src/lib/normalizeDefinition.ts
Labels: Type - Feature

#84 Add logging to @scrabble-solver/dictionaries
  packages/dictionaries/package.json
  packages/dictionaries/src/Dictionaries.ts
  packages/dictionaries/src/lib/downloadDictionary.ts
Labels: Type - Chore

#85 Use single keydown event handler for board navigation
  packages/scrabble-solver/src/components/Board/Board.tsx
  packages/scrabble-solver/src/components/Board/BoardPure.tsx
  packages/scrabble-solver/src/components/Board/components/Cell/Cell.module.scss
  packages/scrabble-solver/src/components/Board/components/Cell/Cell.tsx
  packages/scrabble-solver/src/components/Board/components/Cell/CellPure.tsx
  packages/scrabble-solver/src/components/Board/hooks/useGrid.ts
  packages/scrabble-solver/src/components/Board/lib/getPositionInGrid.ts
  packages/scrabble-solver/src/components/Board/lib/index.ts
  packages/scrabble-solver/src/components/Board/types/index.ts
  packages/scrabble-solver/src/styles/mixins.scss
Labels: Type - Refactoring

#89 Add sidebar with remaining tiles
  packages/scrabble-solver/src/components/KeyMap/KeyMap.tsx
  packages/scrabble-solver/src/components/NavButtons/NavButtons.module.scss
  packages/scrabble-solver/src/components/NavButtons/NavButtons.tsx
  packages/scrabble-solver/src/components/RemainingTiles/RemainingTiles.module.scss
  packages/scrabble-solver/src/components/RemainingTiles/RemainingTiles.tsx
  packages/scrabble-solver/src/components/RemainingTiles/index.ts
  packages/scrabble-solver/src/components/Settings/Settings.tsx
  packages/scrabble-solver/src/components/SquareButton/SquareButton.module.scss
  packages/scrabble-solver/src/components/Tile/Tile.module.scss
  packages/scrabble-solver/src/components/Tile/Tile.tsx
  packages/scrabble-solver/src/components/Tile/TilePure.tsx
  packages/scrabble-solver/src/components/index.ts
  packages/scrabble-solver/src/i18n/en.json
  packages/scrabble-solver/src/i18n/fr.json
  packages/scrabble-solver/src/i18n/pl.json
  packages/scrabble-solver/src/icons/index.ts
  packages/scrabble-solver/src/icons/sack.svg
  packages/scrabble-solver/src/pages/index.tsx
  packages/scrabble-solver/src/parameters/index.ts
  packages/scrabble-solver/src/state/selectors.ts
  packages/scrabble-solver/src/styles/variables.scss
  packages/scrabble-solver/src/types/index.ts
  packages/types/src/Config.ts
Labels: Type - Feature
